version: '3.8'

networks:
  micro-lumen-nest:
    external: true

services:
  nest-app:
    container_name: nest-app
    build:
      context: ./
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src
      - /usr/src/node_modules  # Evita conflitos com os node_modules do host
    environment:
      KAFKA_BROKER: kafka:9092
    networks:
      - micro-lumen-nest
